# 定义的以下变量可以使用site.变量名访问
title:             浙工大网安院无人组
email:             562339477@qq.com
author:            bowenWang
url:               "http://menial-love.github.io/"

members:
  - name: 大娃
    photo: /img/大娃.jpeg
  - name: 二娃
    photo: /img/二娃.jpeg
  - name: 三娃
    photo: /img/三娃.jpeg
  - name: 四娃
    photo: /img/四娃.jpeg
  - name: 五娃
    photo: /img/五娃.jpeg
  - name: 六娃
    photo: /img/六娃.jpeg
  - name: 七娃
    photo: /img/七娃.jpeg

# Build settings
markdown:          kramdown
paginate:          1

plugins:
  - jekyll-feed
  - jekyll-paginate
